---
- name: Deploy React and Django app to Kubernetes
  hosts: localhost
  tasks:
    - name: Apply Kubernetes namespace
      command: kubectl apply -f ../k8s/namespace.yaml

    - name: Deploy Backend
      command: kubectl apply -f ../k8s/backend-deployment.yaml

    - name: Deploy Frontend
      command: kubectl apply -f ../k8s/frontend-deployment.yaml
